### ISSUE TITLE
Redis, SSDB、Hazelcast 熟悉 ［进行中］

### ISSUE THREAD

**Issue by itang** [itang/todo.itang.me#48]
- [ ] http://stackoverflow.com/questions/4109366/redis-vs-hazelcast
## 相关项目
-  twitter/twemproxy ： redis的负载均衡
## 使用场景
- [ ] Redis作者谈Redis应用场景 http://www.ttlsa.com/redis/redis-the-author-talks-about-redis-application-scenario/
- [ ] 让Redis在你的系统中发挥更大作用  http://database.51cto.com/art/201107/276333.htm
- [ ] 用SSDB快速开发一个微博(Twitter)demo http://www.ideawu.net/blog/archives/747.html
## Redis
- [ ] Redis 作为缓存服务器的配置 https://ruby-china.org/topics/22761
- [ ]  redis commands http://redis.io/commands
- [ ]  redis commands中文版： http://redis.readthedocs.org/en/2.6/key.html
  
  2014-08-19: 看完 key和string部分
- [ ] http://www.blogways.net/blog/2013/06/02/jedis-demo.html
- [ ] https://github.com/xetorthio/jedis/wiki
- [ ] Dynamic sharding implementation 动态（运行时）分片实现 https://github.com/xetorthio/jedis/pull/174
- [ ] http://pauladamsmith.com/articles/redis-under-the-hood.html#processing-a-request-returning-a-response
### 数据类型

```
String(字符串)
Hash(哈希表)
List(列表)
Set(集合)
有序集(Sorted set)
```
### 模型

Pub/Sub(发布/订阅)
### 使用场景
- 保存用户信息 redis.set(uid, user_info_str) 
- 获取排行榜: redis.zRangeByScore(xxx_index_, 0, 10)
### 相关库和工具
- https://github.com/mrniko/redisson
### 资料
- [ ] 通过tests熟悉ssdb的支持的数据类型和命令 https://github.com/nutzam/ssdb4j/blob/master/src/test/java/org/nutz/ssdb4j/impl/SimpleClientTest.java
### 部署建议:

http://www.ideawu.net/blog/archives/770.html

> 我们是单个实例百亿条数据, 使用双主架构, 仅使用其中一个作为写, 故障时整体切换到另一
> 
> ssdb 的双主配置比较简单, 只需要将 replication.type 设为 mirror, 然后各指向对方即可.
### 搭建与测试

配置项：

Memory Usage：

```
cache_size + write_buffer_size * 66 + 32
```

默认的memory usage of a ssdb-server instance是：

 500  + 64 \* 66 + 32 =  4756 (M)
#### 简单启动

```
 ./ssdb-server ssdb.conf
```
#### Setting up master/slave distribution

Master-Slave:

server 1:  ./ssdb-server ssdb.conf

```
replication:
    slaveof:
```

server 2:  ./ssdb-server ssdb_slave.conf

```
replication:
    slaveof:
        id: svc_1
        # sync|mirror, default is sync
        type: sync
        ip: 127.0.0.1
        port: 8888
```

Master-Master:

server 1:

```
replication:
    slaveof:
        id: svc_2
        # sync|mirror, default is sync
        type: mirror
        ip: 127.0.0.1
        port: 8889
```

server2:

```
replication:
    slaveof:
        id: svc_1
        # sync|mirror, default is sync
        type: mirror
        ip: 127.0.0.1
        port: 8888
```
#### 通过telnet 测试

```
➜  ssdb-master  telnet localhost 8888
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
3
get
3
key

9
not_found

3
set
3
aaa
3
bbb

2
ok
1
1

3
get
3
aaa

2
ok
3
bbb

```
